// <auto-generated />
using EmployeeManagementApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221124114922_MigrationSeedEmployee4.0")]
    partial class MigrationSeedEmployee40
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeeManagementApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "sam@micro.com",
                            Name = "Sam"
                        },
                        new
                        {
                            Id = 2,
                            Department = 3,
                            Email = "otto@micro.com",
                            Name = "Otto"
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "alex123@micro.com",
                            Name = "Alex"
                        },
                        new
                        {
                            Id = 4,
                            Department = 0,
                            Email = "henry@micro.com",
                            Name = "Henry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
